databases:
  - name: price-db
    plan: free
    databaseName: price_alerts
    user: metabase

services:
  - type: web
    name: gradio-price-alert
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: price-db
          property: connectionString
      - key: GRADIO_ANALYTICS_ENABLED
        value: "false"