services:
  # --- Gradio (sin cambios) --------------------------
  - type: web
    name: gradio-price-alert
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker app:app --bind 0.0.0.0:$PORT
    envVars:
      - key: DATABASE_URL
        fromDatabase: price-db

  # --- Metabase (antes “private”) --------------------
  - type: web          #  <-- CAMBIO: era “private”
    name: metabase
    env: docker
    plan: free
    dockerfilePath: Dockerfile.metabase
    autoDeploy: false
    envVars:
      - key: MB_DB_CONNECTION_URI
        fromDatabase: price-db